### ISSUE TITLE
Convert file to php that reads from google sheets

### ISSUE THREAD

**Issue by stacksavings** [StackSavingsTeam/googlesheetslayout#1]
This file needs to be converted to a php file that reads from Google sheets so that the text fields are editable:

https://github.com/StackSavingsTeam/googlesheetslayout/blob/master/mastenia/index.html

For now, only do this for the text within the top part of the page, where it the form is, etc.. not below this colored background area where the form is.

----
Example of other file that does this:

https://github.com/StackSavingsTeam/googlesheetslayout/blob/master/andrew/andrew.php

**Comment by avi-stacksavings** [comment]
FTP URL for tested on: http://servicejoin.com/mastenia_test2/index.php

the page successfully reads from google sheet to edit the page.
Google sheet link:  https://docs.google.com/spreadsheets/d/1HBZybnUJOdUokHZIU_dPeK1-2xhT3u5yAoH911cuij4/edit#gid=1720958384
tab: mastenia

For verification:
edited tags in google sheet and refreshed the FTP URL to confirm the changes.
