### ISSUE TITLE
Facebook button in wrong spot

### ISSUE THREAD

**Issue by stacksavings** [StackSavingsTeam/googlesheetslayout#10]
When checking here:

http://servicejoin.com/livre-4/index.php

It is obvious the facebook button is in the wrong spot as it is covering some text.. need to make this at least appear somewhat decently, should go in area where there is no text so it's not overlapping. After login it also has text that overlaps another area. This should be obvious just from viewing page that it isn't right..

**Comment by kuljeetbabber** [comment]
@avidayal91 See button placement here http://bagpacks-avidayal91.c9users.io/livre-4/index.php

**Comment by avi-stacksavings** [comment]
FTP URL: http://servicejoin.com/livre-4/index.php

**Comment by avi-stacksavings** [comment]
ready for final verification
