### ISSUE TITLE
Feature - Make images editable

### ISSUE THREAD

**Issue by stacksavings** [StackSavingsTeam/googlesheetslayout#11]
Layout: livre-4

Make all images on the page editable so that it pulls a url from a field in the sheet that currently holds the text values ( https://docs.google.com/spreadsheets/d/1HBZybnUJOdUokHZIU_dPeK1-2xhT3u5yAoH911cuij4/edit#gid=440551199 )

Each image fieldname should be in the format of:

image-<fieldname> 

(for example: image-main, image-section1) Just use names that make sense based on where in page image is, etc

**Comment by kuljeetbabber** [comment]
images are editable with format image-
example;
image-logo
image-main
image-section-1
image-section-2
image-emp-1
image-emp-2
image-emp-3
image-emp-4

**Comment by avi-stacksavings** [comment]
FTP URL: http://servicejoin.com/livre-4/index.php

**Comment by avi-stacksavings** [comment]
ready for final verification
