### ISSUE TITLE
Feature - add variable page elements

### ISSUE THREAD

**Issue by stacksavings** [StackSavingsTeam/googlesheetslayout#12]
Layout: livre-4

Check the google sheet for these fields:

col_1_head
col_content_1
col_2_head
col_content_2
col_3_head
col_content_3
col_4_head
col_content_4

Then check where these correspond to in the layout.

You can see that these are 4 different "elements", each of these "elements" has title, icon image and short text.

In a real layout we may not actually have 4 of these to put in (like just 2 or 3) or, we may have more, like 6 or 7 (these are just examples, don't take literally)

Instead of having the page have just 4 of these we want to have however many are needed automatically.

The way to do this is to make the php code check for any elements that have names like this (note, you should change so that it has the numbers at the end of the name instead of in the middle, so "col_1_head would be col_head_1 instead"):

col_head_
col_content_

So the PHP code would get all fields that start with the prefixes for these and then iterate though and make a separate element for each number. So, the page should only show the exact number of elements that are defined in the google sheet, no more and no less.

**Comment by avi-stacksavings** [comment]
Google SHeet link: https://docs.google.com/spreadsheets/d/1HBZybnUJOdUokHZIU_dPeK1-2xhT3u5yAoH911cuij4/edit#gid=1394763281

**Comment by avi-stacksavings** [comment]
issue fixed: 

FTP URL: http://servicejoin.com/livre-4/index.php

**Comment by avi-stacksavings** [comment]
ready for final verification

**Comment by avi-stacksavings** [comment]
Reopening issue because of bad code.

**Comment by amitonkare** [comment]
The index page is hardcoded with col_1_head col_content_1 tags. It needs to be dynamic. just compare "col_head_" and the appended number can be extracted and checked if it is odd/even.

**Comment by avi-stacksavings** [comment]
Marking this as complete.  as this functionality working on servicejoin.com/livre-4/index.php
 for CSS adding new issue.

**Comment by avi-stacksavings** [comment]
Pending for final approval

**Comment by avi-stacksavings** [comment]
Google SHeet link: https://docs.google.com/spreadsheets/d/1HBZybnUJOdUokHZIU_dPeK1-2xhT3u5yAoH911cuij4/edit#gid=1394763281
Tab name: livre-lead
