### ISSUE TITLE
Not Mobile Responsive

### ISSUE THREAD

**Issue by avi-stacksavings** [StackSavingsTeam/googlesheetslayout#13]
Following mobile responsive issues:

1. able to scroll right
2. 2nd section overlaps with the 3rd one.
3.in 4th section "image goes here" section is going far right in mobile and also overlapping with next section.

**Comment by avi-stacksavings** [comment]
Pending for final approval:
Marking this as complete.  as this functionality working on servicejoin.com/livre-4/index.php
 for CSS adding new issue

**Comment by stacksavings** [comment]
@avi-stacksavings  again, you need to be putting FTP links for final verification, I have already mentioned this before...

**Comment by avi-stacksavings** [comment]
FTP URL: servicejoin.com/livre-4/index.php
