### ISSUE TITLE
Implement same functionality for other elements as done for Issue #12

### ISSUE THREAD

**Issue by stacksavings** [StackSavingsTeam/googlesheetslayout#14]
In the livre4 layout, implement the same functionality as was done in ( https://github.com/StackSavingsTeam/googlesheetslayout/issues/12 )

For the element blocks that start with these:

testimonial_content_
image-emp-
emp_
job_title_

So, each "block" contains one element each that starts with the above. The names of the elements should be changed to be more clearly understandable thoug, so that they all start with "testimonial" to indicate they are part of a grouping:

testimonial_content_
testimonial_image-emp-
testimonial_emp_
testimonial_job_title_

**Comment by amitonkare** [comment]
Need to rewrite html/css. The code has become complicated due the quality of css that was downloaded from the theme website. It will be good for further maintaining the code too.

**Comment by avi-stacksavings** [comment]
Marking this as complete.  as this functionality working on servicejoin.com/livre-4/index.php
 for CSS adding new issue

Pending final approravl

**Comment by stacksavings** [comment]
@avi-stacksavings need to mention FTP link for any final verification.

**Comment by avi-stacksavings** [comment]
FTP URL: servicejoin.com/livre-4/index.php

**Comment by avi-stacksavings** [comment]
Google SHeet link: https://docs.google.com/spreadsheets/d/1HBZybnUJOdUokHZIU_dPeK1-2xhT3u5yAoH911cuij4/edit#gid=1394763281
Tab name: livre-lead
