### ISSUE TITLE
Some text and links not editable

### ISSUE THREAD

**Issue by stacksavings** [StackSavingsTeam/googlesheetslayout#15]
As has been mentioned before, all text and links must be editable, check again that all are and make sure to make these editable:

< < Free for a limited time

Smooth scroll to top  >  >

Built using the Unbounce Landing Page Platform

**Comment by avi-stacksavings** [comment]
Marking this as complete.  as this functionality working on servicejoin.com/livre-4/index.php

Pending final approval

**Comment by stacksavings** [comment]
@avi-stacksavings  again need links for final verififcation from ftp

**Comment by avi-stacksavings** [comment]
FTP URL: servicejoin.com/livre-4/index.php

**Comment by avi-stacksavings** [comment]
Google SHeet link: https://docs.google.com/spreadsheets/d/1HBZybnUJOdUokHZIU_dPeK1-2xhT3u5yAoH911cuij4/edit#gid=1394763281
Tab name: livre-lead

**Comment by avi-stacksavings** [comment]
These 2 fields not editable from the sheet:
image-logo
image-main

Sheet used: https://docs.google.com/spreadsheets/d/1HBZybnUJOdUokHZIU_dPeK1-2xhT3u5yAoH911cuij4/edit#gid=440551199

Tested on: http://servicejoin.com/livre-4/index.php

**Comment by stacksavings** [comment]
@avi-stacksavings  status? who is working on this?

**Comment by stacksavings** [comment]
Image edit not working also in top images on production

**Comment by avi-stacksavings** [comment]
@stacksavings Pending final approval.

it required to check in latest index.php file.
URL: stacksavings.com/connect/livre-4/?page=test-page
