### ISSUE TITLE
Layout: Lead-gen implementation

### ISSUE THREAD

**Issue by avi-stacksavings** [StackSavingsTeam/googlesheetslayout#17]
Use "googlesheet-layouts2" workspace in [C9 ](https://c9.io/)(check with Avi for C9 credentials if not provided)

Layout name: lead-gen 

URL: https://googlesheet-layouts2-stacksavings.c9users.io/lead-gen/unbouncepages.com/alphapix/preview/mira/leadgen/index.html

Task1. Need to make layout editable using googlesheet (follow isntructions from [here ](https://github.com/StackSavingsTeam/googlesheetslayout/wiki/Task:-Make-new-layout-editable))

Need to use this [sheet](https://docs.google.com/spreadsheets/d/1HBZybnUJOdUokHZIU_dPeK1-2xhT3u5yAoH911cuij4/edit#gid=440551199) but have to make new tab named "lead-gen" and need to save all tags there.

**Comment by avi-stacksavings** [comment]
@stacksavings  added info here for Aamir

**Comment by stacksavings** [comment]
@avidayal91 You need to be updating these once completed....
