### ISSUE TITLE
Layout: Tech-solution implementation

### ISSUE THREAD

**Issue by avi-stacksavings** [StackSavingsTeam/googlesheetslayout#19]
Use "googlesheet-layouts4" workspace in C9 (check with Avi for C9 credentials if not provided)

Layout name: tech-solution

URL: https://googlesheet-layouts4-stacksavings.c9users.io/tech-solution/portfolio.dotadz.com/index.html

Task1. Need to make layout editable using googlesheet (follow instructions from [here](https://github.com/StackSavingsTeam/googlesheetslayout/wiki/Task:-Make-new-layout-editable) )

Need to use this [sheet](https://docs.google.com/spreadsheets/d/1HBZybnUJOdUokHZIU_dPeK1-2xhT3u5yAoH911cuij4/edit#gid=440551199) and use tags from livre-lead

**Comment by stacksavings** [comment]
@avi-stacksavings  you need to be updating these once completed.
