### ISSUE TITLE
Implement facebook login within the form

### ISSUE THREAD

**Issue by stacksavings** [StackSavingsTeam/googlesheetslayout#2]
1) Edit this layout so that, instead of what shows now in the form initially it should show the facebook login button:

https://github.com/StackSavingsTeam/googlesheetslayout/blob/master/mastenia/index.html

Implement this so it is fully working with login (where it writes user info to google sheet upon login).

Make sure to pay attention to code comments I already made as this cannot use hard-coded c9 url, etc it has to be able to be uploaded into FTP and work without using c9. Any common code needs to go under /vendor/stacksavings (at root level)

2) So, after user clicks facebook login and it succeeds it should then show step #2 of form (like the way it is now that it goes to next section after submitting first.. however, what is currently step #1 needs to become step #2, so that it shows the name, last name, your email.. fields as step #2 (so user can only submit this after they have clikced the facebook button and it succeeded.

3) need to make sure the form submission for step #2 now works properly, it was working before to submit to the same google sheet we have been using

**Comment by avi-stacksavings** [comment]
FTP URL for tested on: http://servicejoin.com/mastenia_test2/index.php

Google sheet link where data gets written : https://docs.google.com/spreadsheets/d/1DLkfaQ_6rfLWMHEBa8-kHFgIm9SjRda2AY5z2BKrhAI/edit#gid=0

For verification:
CLicked on fb button and logged in using the valid FB account
after logged in suing fb button, it asked to fill up the remaining form.
Once all steps of formed filled in then submitted
To confirm, opened the above mentioned google sheet and checked the responses there.

Successfully writes data in googlesheet for each fb logina dn form fill combined.
