### ISSUE TITLE
CSS - Livre-4 CSS issue

### ISSUE THREAD

**Issue by avi-stacksavings** [StackSavingsTeam/googlesheetslayout#22]
Layout name: Livre-4

Check issues here in this URL: https://googlesheet-layouts4-stacksavings.c9users.io/livre-4/

CSS issue at sections where we made it dynamic, like in last section you see employe testimonial getting out of the section.

Also same issues in mobile (adding screenshots below)

![screenshot_20170402-003932](https://cloud.githubusercontent.com/assets/20572760/24581691/e23130ec-173d-11e7-9ede-1b0cd36d8005.png)
![screenshot_20170402-003939](https://cloud.githubusercontent.com/assets/20572760/24581697/155a102e-173e-11e7-82d7-29dd9c106d26.png)

**Comment by avi-stacksavings** [comment]
Some elements which are already deleted from google sheet still showing in both the sections.. in a repetitive manner. Check screenshots below.
![screenshot_300](https://cloud.githubusercontent.com/assets/20572760/24589740/4b88b1ea-17fd-11e7-9eb4-e635d357a38c.png)
![screenshot_301](https://cloud.githubusercontent.com/assets/20572760/24589741/4b8fb012-17fd-11e7-839b-353fa7354434.png)

**Comment by aamirsatti** [comment]
> These values are there in sheet,,  but are too below at line 78
 


![issue](https://cloud.githubusercontent.com/assets/11290725/24590216/ebd5d81c-1802-11e7-8cab-c9934a6dad31.png)

**Comment by avi-stacksavings** [comment]
Tested on: http://servicejoin.com/livre-4/index.php
Pending final approval
@stacksavings
