### ISSUE TITLE
CSS - Livre-4: Dynamic elements are not in sequence in mobile view

### ISSUE THREAD

**Issue by avi-stacksavings** [StackSavingsTeam/googlesheetslayout#23]
In Googlesheet elements added are in this order

**First dynamic section**
col_head_1	1 How to Make Landing Pages
col_content_1	1 Using psychology & persuasive design to increase conversions
col_head_2	2 Conversion Centered Design
col_content_2	2 Using psychology & persuasive design to increase conversions
col_head_3	3 The Guide to Email Marketing
col_content_3	3 Using psychology & persuasive design to increase conversions
col_head_4	4 lalal
col_content_4	4 xcvxv

**Second dynamic section**
testimonial_content_1	1 Pop culture is not about depth. .....
testimonial_content_2	2 Pop culture is not about depth....
testimonial_content_3	3 Pop culture is not about depth....
testimonial_content_4	4 Pop culture is not about depth....

But in mobile view sequence seems disturbed, though its working fine in desktop view. 
(check mobile screenshots
![screenshot_20170402-235045](https://cloud.githubusercontent.com/assets/20572760/24589866/c7f4328e-17ff-11e7-982d-d92e971d9d38.png)
![screenshot_20170402-235030](https://cloud.githubusercontent.com/assets/20572760/24589865/c7f31db8-17ff-11e7-8fda-781de0ca831f.png)

 below)

**Comment by aamirsatti** [comment]
This Ticket is done.

**Comment by stacksavings** [comment]
@avi-stacksavings  need to test this and also figure why it is saying stacksavings committed it (when you check actual commit from above)

**Comment by aamirsatti** [comment]
It is showing my name, 
 " aamirsatti pushed a commit that referenced this issue 12 hours ago "

**Comment by avi-stacksavings** [comment]
@stacksavings yea here in thread it is showing his name but not there in commit section:
"aamirsatti pushed a commit that referenced this issue 15 hours ago" from this issue thread

**Comment by avi-stacksavings** [comment]
Tested on: http://servicejoin.com/livre-4/index.php
Sheet from where layout reads data: https://docs.google.com/spreadsheets/d/1HBZybnUJOdUokHZIU_dPeK1-2xhT3u5yAoH911cuij4/edit
tab: livre-lead
Pending final approval
