### ISSUE TITLE
CSS - livre4 layout - facebook button not centered on mobile

### ISSUE THREAD

**Issue by stacksavings** [StackSavingsTeam/googlesheetslayout#25]
This can be checked by starting in a regular web browser and re-sizing the page to be mobile size, you will see, after a certain point, that the facebook button gets off center. It should not do this, it should instead always stay centered regardless of screen size. Any text above / below it should also be centered in the same way.

EDIT: even on regular desktop view it is not centered properly it seems.

**Comment by avi-stacksavings** [comment]
@stacksavings 
Tested on: http://servicejoin.com/livre-4/index.php

Pending final approval

**Comment by stacksavings** [comment]
This isn't fixed actually. It seems at least on Firefox to be broken when I check:

http://stacksavings.com/connect/livre-4/index.php

List what browsers tested in.

@avi-stacksavings
