### ISSUE TITLE
Mistakes when cloning layout

### ISSUE THREAD

**Issue by stacksavings** [StackSavingsTeam/googlesheetslayout#26]
Need to look into what is going on as far as how this happened.

In livre-4/index.php there are a bunch of files like this:

https://d9hhrg4mnvzow.cloudfront.net/unbouncepages.com/livre-lead-gen/wgqbmg-livre-v-line_0050b70050b7000000.png

This is obviously wrong as it is pulling from third party host, these files should have been pulled in as part of the initial clone and referenced via relative paths. Need to figure how this happened and how to prevent it in the future. We cannot be linking to third party sites.

This all has to be cleaned up so that no external files like this are being referenced, rather, all must be hosted as part of our own layout.

**Comment by avi-stacksavings** [comment]
@stacksavings i checked above issues.. originally i think these files are already hosted on external location. but by cloning i was able to get all files locally.. so it was makes folder structure as per the path online..
these all files are available offline in cloned (downloaded) folder.

What we can do is, we can change folder name and lets says it should call images and have to change path in index.php too..

**Comment by stacksavings** [comment]
No, this is not the issue, again, it is pulling from the external sites in the url's, check them carefully.. yes, the files were dowloaded but, No, the layout is not using them, it is using the ones from the original site.

**Comment by stacksavings** [comment]
@avi-stacksavings  need update on this

**Comment by avi-stacksavings** [comment]
@stacksavings 
in HTTrack, under "Set options" menu, need to go into "Scan Rules" tab  need to check the checkboxes where it mentions image files and video files extensions
![screenshot_302](https://cloud.githubusercontent.com/assets/20572760/24629419/8d145d7e-18d6-11e7-8728-72a2856ec920.png)
. (refer screenshot below)

**Comment by avi-stacksavings** [comment]
Also, during initial process need to change URLs in index.html file

url can be like this:
livre-testing/d9hhrg4mnvzow.cloudfront.net/unbouncepages.com/livre-lead-gen/sqx67g-livre-logo.png

instead of like this
../../d9hhrg4mnvzow.cloudfront.net/unbouncepages.com/livre-lead-gen/1h5crco-livre-user-3.jpg

**Comment by stacksavings** [comment]
I don't know why this was closed, this was not fix in the layout:

https://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js" type="text/javascript"></script>
<script src="https://d2y5whbil7yeo8.cloudfront.net/published/jquery.validate.min-3b750e1.z.js"

you can clearly see that they are all like the above link in this one:

http://servicejoin.com/livre-4/index.php

You are supposed to actually fix this issue as part of the ticket, not just put a bunch of info above.

A ticket is definitely not the right place for info like this either, rather, you are supposed to document the info in the appropriate place and link to it from the ticket as was mentioned previously.

**Comment by avi-stacksavings** [comment]
all URL changed...  and pushed ... tested on 
servicejoin.com/livre-4/index.php

@stacksavings Pending final approval

**Comment by avi-stacksavings** [comment]
@stacksavings one issue there.
for http://stacksavings.com/connect/livre-4/

i had to add the url as:
 /connect/livre-4/d9hhrg4mnvzow.cloudfront.net/unbouncepages.com/livre-lead-gen/wgqbmg-livre-v-line_0050b70050b7000000.png

but for servicejoin.com/livre-4/index.php
i had to make url as:
/livre-4/d9hhrg4mnvzow.cloudfront.net/unbouncepages.com/livre-lead-gen/wgqbmg-livre-v-line_0050b70050b7000000.png

so this is where it required 2 different URLs in index php for dev and prod versions.

**Comment by stacksavings** [comment]
Ok maybe using relative path will be better in future, did you commit a change on this yet then or what?

**Comment by avi-stacksavings** [comment]
i did commit with /livre-4 as prefix, which will work in servicejoin FTP.
but didnt commit with /connect/livre-4/ ... just changed values in index.php and downloaded for stacksavings FTP.

**Comment by stacksavings** [comment]
whats the status of this then @avi-stacksavings  ?
