### ISSUE TITLE
JavaScript - Facebook JavaScript logic needs to be pulled out into common file and put under vendor folder

### ISSUE THREAD

**Issue by stacksavings** [StackSavingsTeam/googlesheetslayout#28]
The facebook JavaScript logic needs to be extracted fully from the livre-4 layout and put in common files, underr /vendor folder so that it can be used by any layout and not be specific to one layout.

There is logic in:

/livre-4/index.php
livre-4/js_code.js

and possibly other places.. this all needs to be extracted from there and put into the common place and fully tested so that it is working. Any specific logic for this within livre-4 must then be deleted.

**Comment by cyberdypro** [comment]
@stacksavings I have completed this task. For now, if we want to use facebook login we just inject php script `$facebookIntergration = FacebookIntegration::getInstance('[FB_APP_ID]', '[SHEET_NAME]')->setLoginCallback('[CLIENT_CALLBACK]');` also call `<?php echo $facebookIntergration->getInitScripts(); ?>` under `<body>` tag. [CLIENT_CALLBACK] is a javascript function, it will invoke after facebook logged in, so user can use this function for handle another stuff. User can put facebook login button anywhere with script `<?php echo $facebookIntergration->getLoginButton() ?>`. Please check and let me know if have any incorrect

**Comment by stacksavings** [comment]
@avi-stacksavings have you tested this at all? no comment from you on this yet......

**Comment by avi-stacksavings** [comment]
Earlier I haven't commented coz FB button wasn't working in Stacksavings domain.

Tested on both the URLs
servicejoin.com/livre-4/index.php
http://stacksavings.com/connect/livre-4/

FB button working good on both.

@stacksavings Pending final approval.

**Comment by stacksavings** [comment]
Code will still need to be reviewed later but will close for now as it seems to be working.
