### ISSUE TITLE
facebook button didnt work after pushing to FTP as a newlayout

### ISSUE THREAD

**Issue by avi-stacksavings** [StackSavingsTeam/googlesheetslayout#3]
uploaded "mastenia" files in FTP as a new layout. But after login with facebook button it doesnt proceeds to actual form.
The facebook button keeps on showing even after the login done.
No data reflected in google sheet: https://docs.google.com/spreadsheets/d/1DLkfaQ_6rfLWMHEBa8-kHFgIm9SjRda2AY5z2BKrhAI/edit#gid=0

URL: http://servicejoin.com/mastenia_test2/index.php

however old html link is working fine: http://servicejoin.com/mastenia_test/index.html
but we need index.php url to be working as it reads from the sheet to edit the page.

additionally,  tried adding this URL: http://servicejoin.com/vendor/stacksavings/post.php
in js_code.js file in var url
but this didnt work either.

**Comment by vksbhandary** [comment]
FB login is working fine now.
FB login api needs scope variable 
(in html it is assigned on fb login button by adding attribute data-scope="email,public_profile" )

**Comment by avi-stacksavings** [comment]
FTP URL: http://servicejoin.com/mastenia_test2/index.php

tested on above ftp url and now Facebook buttons working fine followed by the actual form and getting data saved in google sheet https://docs.google.com/spreadsheets/d/1DLkfaQ_6rfLWMHEBa8-kHFgIm9SjRda2AY5z2BKrhAI/edit#gid=0
