### ISSUE TITLE
Need to add production config file

### ISSUE THREAD

**Issue by avi-stacksavings** [StackSavingsTeam/googlesheetslayout#31]
Production config file needs to be added by making a duplicate of current and name it by adding  "_prod" as a suffix in the current name.

**Comment by avi-stacksavings** [comment]
file checked in 

Pending final approval.

**Comment by stacksavings** [comment]
nope, go ahead and double check this, you have the same file for the layout values sheet ID ("layout_values_sheet=layout_values_sheet=1HBZybnUJOdUokHZIU_dPeK1-2xhT3u5yAoH911cuij4") in both the production config and the regular config.

**Comment by stacksavings** [comment]
@avi-stacksavings

**Comment by stacksavings** [comment]
because of this you have no set the code to always use the production sheet, even for devs, etc and in servicejoin.com url, this obviously needs to be fixed or it will block future development and confuse developers.

**Comment by avi-stacksavings** [comment]
@stacksavings  made correction.
Pushed the latest with correctr sheet ID

Pending final approval.

**Comment by stacksavings** [comment]
@avi-stacksavings  did you test it?

url's used to test, etc???

**Comment by avi-stacksavings** [comment]
http://servicejoin.com/livre-4/index.php
http://stacksavings.com/connect/livre-4/

@stacksavings yes tested.
