### ISSUE TITLE
Production Livre-4: form not saving data in production sheet

### ISSUE THREAD

**Issue by avi-stacksavings** [StackSavingsTeam/googlesheetslayout#32]
Using production URL: stacksavings.com/connect/livre-4/
form after fb login should save records in https://docs.google.com/spreadsheets/d/1cBWku3K8qpdxYUpnQokaf3g3UomkxbDFax04nss_f2c/edit#gid=1980407392

**Comment by avi-stacksavings** [comment]
Test on URL: http://stacksavings.com/connect/livre-4/

Form and FB data recording successfully in: 
https://docs.google.com/spreadsheets/d/1cBWku3K8qpdxYUpnQokaf3g3UomkxbDFax04nss_f2c/edit#gid=1980407392

@stacksavings Pending final approval

**Comment by stacksavings** [comment]
No, this is not working. It is likely related to cloudflare, however, so am looking into it.

**Comment by avi-stacksavings** [comment]
Test on URL: http://stacksavings.com/connect/livre-4/

Form and FB data recording successfully in:
https://docs.google.com/spreadsheets/d/1cBWku3K8qpdxYUpnQokaf3g3UomkxbDFax04nss_f2c/edit#gid=1980407392

@stacksavings  Pending final approval.
