### ISSUE TITLE
Clicking facebook button production url writes to development sheet

### ISSUE THREAD

**Issue by stacksavings** [StackSavingsTeam/googlesheetslayout#34]
Clicking the facebook button here:

http://stacksavings.com/connect/livre-4/index.php

Is writing to the dev version of the sheet:

https://docs.google.com/spreadsheets/d/1E_6-X5gESKCMWK4OAJP_pr2YGwYYB5SS4XlwJlBcxS0/edit#gid=1739651797

I'm guessing the code is not right to where it uses the value in the properties file??

The form submission works correctly, it submits here:

https://docs.google.com/spreadsheets/d/1cBWku3K8qpdxYUpnQokaf3g3UomkxbDFax04nss_f2c/edit#gid=1980407392

Both the facebook button write and the form submission need to write to the same sheet definied in the properties file as "facebook_submissions_sheet".

**Comment by stacksavings** [comment]
closing this, it was just a config issue, the issue is actually with the form submission (non facebook), will open a new ticket for that.

**Comment by avi-stacksavings** [comment]
Test on URL: http://stacksavings.com/connect/livre-4/

Form and FB data recording successfully in:
https://docs.google.com/spreadsheets/d/1cBWku3K8qpdxYUpnQokaf3g3UomkxbDFax04nss_f2c/edit#gid=1980407392

@stacksavings Pending final approval
