### ISSUE TITLE
Make the url for the form submission read from config file

### ISSUE THREAD

**Issue by stacksavings** [StackSavingsTeam/googlesheetslayout#35]
Need to set the url value for the form submission (it calls a google script) to be pulled from the config file, so we need a value in both the prod and regular version. Avi can add info here on which url to use for each. 

Dev version script: https://script.google.com/macros/s/AKfycbzY4abBoaoIkS9DNlRsd_7sdgTk73jgzvTRU7t0EV1V3v61D0Q/exec
Dev version of sheet to save data in:
https://docs.google.com/spreadsheets/d/1E_6-X5gESKCMWK4OAJP_pr2YGwYYB5SS4XlwJlBcxS0/edit#gid=0

Production script: https://script.google.com/macros/s/AKfycbzIRe7VO2dowq0wKQFEk7tTRoG7f4IEVx-jcZm4omxeRRrgKVA/exec

Production sheet to save data in:
https://docs.google.com/spreadsheets/d/1cBWku3K8qpdxYUpnQokaf3g3UomkxbDFax04nss_f2c/edit

**Comment by cyberdypro** [comment]
@stacksavings I have made the way to change form submission endpoint, please put your macro sheet url at `vendor/stacksavings/google_sheet_definitions.properties` file with key  `google_submissions_macro`

**Comment by avi-stacksavings** [comment]
Test on both the URL: 
**Dev version:** http://servicejoin.com/livre-4/index.php
**Production version:** http://stacksavings.com/connect/livre-4/

Writing form data successfully in their respective sheet.
**Dev sheet:** https://docs.google.com/spreadsheets/d/1E_6-X5gESKCMWK4OAJP_pr2YGwYYB5SS4XlwJlBcxS0/edit?usp=drive_web
**Production sheet:** https://docs.google.com/spreadsheets/d/1cBWku3K8qpdxYUpnQokaf3g3UomkxbDFax04nss_f2c/edit

@stacksavings Pending final approval.

**Comment by stacksavings** [comment]
It looks like both prod and default properties using same version?

**Comment by avi-stacksavings** [comment]
no, each using different sheet.

**Comment by stacksavings** [comment]
ok the prefix for them is the same so it seemed that way, was checking from mobile, will close.
