### ISSUE TITLE
Change production google macro for form to send email to admin@stacksavings.com also make sure all links added in references sheet

### ISSUE THREAD

**Issue by stacksavings** [StackSavingsTeam/googlesheetslayout#36]
- In references sheet, add links for all sheets we use for this, both prod and dev versions 

- change the production google script macro to send emails to admin@stacksavings.com instead of Avi's emai.

**Comment by stacksavings** [comment]
@avi-stacksavings

**Comment by avi-stacksavings** [comment]
I submitted the form with
name: checkl if received	
email: avidayal91@gmail.com
Check if received the email.


Also, added all sheet links in refrence sheet ar row 120.

@stacksavings IF received mark as complete. Pending final approval.

**Comment by stacksavings** [comment]
Received
