### ISSUE TITLE
Marketing - Work on video for marketing

### ISSUE THREAD

**Issue by stacksavings** [StackSavingsTeam/googlesheetslayout#37]
As discussed

**Comment by avi-stacksavings** [comment]
Please check here: https://drive.google.com/drive/folders/0B7YlCjcWh0RIUUY1ZWR3ZGhOOFU
@stacksavings

**Comment by stacksavings** [comment]
**Example videos:**

(check "flexible charging cable video send on Facebook messenger)

https://m.facebook.com/story.php?story_fbid=10207730691980338&id=1684337131

**Key Points:**

- text moves onto screen, doesn't just start off on the video, check effects used in the videos above
- very crisp editing, each scene has to stand alone can't be a whole screencast. Like it should not show any switching of tabs or anything and minimal delays
- pay close attention to timing of video like how long it shows each screen with the text on, etc, this stuff is important
- there is some movement effect they use very often in these too, where it moves slightly, like to left or right, when showing image, they do this with static images but also video I think, can look at doing this.


**Can try this software or another similar to see if it may make it easier/ quicker to make these types of videos:**

https://animoto.com

**Comment by avi-stacksavings** [comment]
Latest Video file name is Stacksavings App 3 in this folder: https://drive.google.com/drive/folders/0B7YlCjcWh0RIUUY1ZWR3ZGhOOFU

Currently, need to work on making it more squared type video so it looks good in mobile devices
