### ISSUE TITLE
Marketing - Layout marketing to show how product works, etc

### ISSUE THREAD

**Issue by stacksavings** [StackSavingsTeam/googlesheetslayout#38]
Have someone work on using the livre-4 to make a page that shows basics of the app, etc and should use attractive images, etc..

**Comment by stacksavings** [comment]
@avi-stacksavings  status?

**Comment by avi-stacksavings** [comment]
@stacksavings I will work on this in my morning

**Comment by avi-stacksavings** [comment]
@stacksavings currently started working on it

**Comment by stacksavings** [comment]
Update?

**Comment by avi-stacksavings** [comment]
I made some changes, but not near complete. Need something to put in testimonial area.
http://servicejoin.com/livre-4/index.php

**Comment by stacksavings** [comment]
no... please don't edit that, that is the main one, you need separate tab for this! Always make new tab for this so it's page, not the main page... @avi-stacksavings Fix this now please and restore to image I had put there in my evening.

**Comment by stacksavings** [comment]
@avi-stacksavings  update this with url, etc of the layout and stautus.

**Comment by avi-stacksavings** [comment]
URL: http://servicejoin.com/livre-4/index.php?page=test-page
Sheet Used: Dev version
Tab Name: livre-lead_test-page

@stacksavings  Not sure what should I add there in testimonial section.

**Comment by stacksavings** [comment]
Ok this is good but please embed video also, you can do this using HTML in Google sheets code,. Use basic HTML to format around it also and get embed code from YouTube after uploading the latest video we put on Facebook

**Comment by stacksavings** [comment]
Also,. Check in Mobile view always. Some text overlaps so need to make shorter. Also or header image make darker. We can't change color of text currently so we need to work around this, you can use tool to darken image like some online tool from a Google search. Generally, it's better to use a darker image anyway with text I think

**Comment by avi-stacksavings** [comment]
added: http://servicejoin.com/livre-4/index.php?page=test-page
