### ISSUE TITLE
Create new layout in project from old panellum code

### ISSUE THREAD

**Issue by stacksavings** [StackSavingsTeam/googlesheetslayout#39]
Get this old project running in c9 workspace:

https://bitbucket.org/stacksavings/stacksavings-360 

Then check the best working layout we have there with 360 image, take just that layout and commit into this new project and call the layout folder "demo-360" and test that it fully works, etc.. we just need this as initial example as we are going to somehow use 360 images in future layout and this way the dev then has the code needed, etc to pull out of there easily and see working example.

**Comment by avi-stacksavings** [comment]
Added the folder named "demo-360"
URL: http://servicejoin.com/demo-360/connect.stacksavings.com/fall-activities-to-do-1/index.html

@stacksavings Pending final approval.
