### ISSUE TITLE
Form steps

### ISSUE THREAD

**Issue by stacksavings** [StackSavingsTeam/googlesheetslayout#4]
The following changes need to be made to the form in the layout.

A) Field display names should be editable but the FieldName's below would be used in the actual code. 

Steps need to be changed to the folllowing:

1) Initial step, just shows the facebook connect button in the area of the form (so no other fields show. There should be text above this that says "Please connect with facebook to get started" (this should be an editable field though also from the google sheet

- There should be a small text link at the bottom that says "continue without facebook login" (this text should be editable via google sheet) where user can click to go to step #2 without facebook login

**Actions:** Once user clicks the Facebook login, it needs to write the name, profile, email, etc data to the google sheet right away. It doesn't matter if they go on to fill out the rest of the form, we need to save this data to the google sheet right away since that provides some base info on the user even if they don't continue with the rest of the form.

- In this sheet can make a tab called "facebook-logins" ( https://docs.google.com/spreadsheets/d/1DLkfaQ_6rfLWMHEBa8-kHFgIm9SjRda2AY5z2BKrhAI/edit#gid=0 ) that just saves basic user info from the login.

**No other fields or buttons should show on this step, so remove the next step button, etc here**

2) For step #2 it should show fields:

first_name (required)
last_name (required)
email (required)
phone (optional)
message optional text area)

- These fields should be auto-filled from the facebook login (if applicable)

Instead of the "Next step" button, this button should say "Submit".

- It should submit the form and write the data to the google sheet in a different tab then is written to from step #1, this tab should be called "form-sbumissions")

Final Notes:

There should be no other steps, so remove step #3

**Comment by avi-stacksavings** [comment]
Tested using this FTP URL: http://servicejoin.com/mastenia_test2/index.php

Tested following things:
1. text and fields are editable - verified and working fine

2. facebook login - working fine but doesn't save fb login info in "facebook-logins" tab in sheet below
https://docs.google.com/spreadsheets/d/1DLkfaQ_6rfLWMHEBa8-kHFgIm9SjRda2AY5z2BKrhAI/edit#gid=1354937986 (Need to fix)

3. Step2 of the form - tested and working fine. saving all form ino in "form submissions" tab in same sheet.

4. form field names are editable by this google sheet. 
https://docs.google.com/spreadsheets/d/1HBZybnUJOdUokHZIU_dPeK1-2xhT3u5yAoH911cuij4/edit#gid=1720958384 (tab "mastenia")

5. all other steps removed from the form.

6. CHnaged Next button to Submit.

**Comment by avi-stacksavings** [comment]
Favcebook logins are getting saved right when user logs in using fb button.
Tested and verified using this URL: http://servicejoin.com/mastenia_test2/index.php
Responses are getting in "facebook-logins" tab in this sheet.
https://docs.google.com/spreadsheets/d/1DLkfaQ_6rfLWMHEBa8-kHFgIm9SjRda2AY5z2BKrhAI/edit#gid=1354937986
