### ISSUE TITLE
Livre-4: White space at bottom 

### ISSUE THREAD

**Issue by avi-stacksavings** [StackSavingsTeam/googlesheetslayout#40]
There is huge white space at the bottom of the layout. 

Can check this URL: http://stacksavings.com/connect/livre-4/?page=test-page

**Comment by cyberdypro** [comment]
@stacksavings @avi-stacksavings i have fixed, please upload and check again

**Comment by avi-stacksavings** [comment]
Tested on
http://servicejoin.com/livre-4/index.php
http://stacksavings.com/connect/livre-4/
http://stacksavings.com/connect/livre-4/?page=test-page

@stacksavings Issue fixed.
Pending final approval.
