### ISSUE TITLE
Analytics code install in prod

### ISSUE THREAD

**Issue by stacksavings** [StackSavingsTeam/googlesheetslayout#41]
We just want analytics code in prod, so don't check into layout code but please put in prod livre-4 layout. We have some old code from before so please use that also reference here where you got that info from so I can review

**Comment by avi-stacksavings** [comment]
added code in production: http://stacksavings.com/connect/livre-4/

Code found here:
https://docs.google.com/document/d/1RnrDGob7hLteHU0-_OcUTwDQgXRiaqpvtl7VZ6HL9hA/edit

**Comment by stacksavings** [comment]
Did you add this in reference sheet?

⁣Sent from BlueMail ​

**Comment by avi-stacksavings** [comment]
@stacksavings Yes it's already linked there in reference.
