### ISSUE TITLE
Marketing: Figure out how to create gif and upload so it works on Facebook

### ISSUE THREAD

**Issue by stacksavings** [StackSavingsTeam/googlesheetslayout#44]
As mentioned in Slack chat, need to figure a way to create a gif that will work on facebook post as this is more favorable for ads than using a video. Please document full info on this.

**Comment by stacksavings** [comment]
@avi-stacksavings

**Comment by avi-stacksavings** [comment]
@stacksavings  Check this
https://storage.googleapis.com/stacksavings-layouts-images/stacksavings_app.gif

**Comment by avi-stacksavings** [comment]
@stacksavings you mentioned google cloud had issue .. so i tested here on https://giphy.com

so uploaded there in giphy and here is URL from there: https://media.giphy.com/media/3o7btLQ2VsLyVAmZzy/giphy.gif

**Comment by avi-stacksavings** [comment]
i used android app called GIF Maker- Gif Editor from Kayak STudio
https://play.google.com/store/apps/details?id=com.kayak.studio.gifmaker&hl=en

@stacksavings

**Comment by stacksavings** [comment]
No

**Comment by avi-stacksavings** [comment]
@stacksavings Giphy working on FB timeline.

**Comment by avi-stacksavings** [comment]
WIki added here: https://github.com/StackSavingsTeam/googlesheetslayout/wiki/Info:-Create-GIF-from-Videos

**Comment by stacksavings** [comment]
@avi-stacksavings  should mark this using label as pending review
