### ISSUE TITLE
Implement module to fix testimonial section in livre-4 layout

### ISSUE THREAD

**Issue by stacksavings** [StackSavingsTeam/googlesheetslayout#48]
Related to #45 and #46

The livre-4 layout has an issue with the testimonials at the bottom as they are broken if try anything other than use exactly 4. So this is good place to try modularized approach just in this one section.

Can you start implementing framework to use modularized approach and make this section a module.

The idea then would be that this module has any needed css as well so it can be used in another layout in the future with minimal hassle.

**Comment by cyberdypro** [comment]
@stacksavings I have completed to implement testimonial as widget with modular approach. I have remaked html/css but just for testimonial section. I've also added Smarty template engine for widget class. For reference how to make testimonial data, please refer at https://docs.google.com/spreadsheets/d/1HBZybnUJOdUokHZIU_dPeK1-2xhT3u5yAoH911cuij4/edit#gid=959060143 under `livre-lead_testimonial` sheet

**Comment by stacksavings** [comment]
@cyberdypro Please do some refactoring as the widget is tied into the livre-4 layout and should not be.

Some new css files, etc were added for the widget, these should not be included direclty in livre4, rather we need a system so they are loaded via the widget. For example, if all widgest need bootstrap, etc then put in some parent widget that all other widgets include. This is best approach I think for this.

The widget has to be able to be easily included in another layout so its not owned or kept inside any one layout but rather in generic place.

Please see my code reading commetns I just made in GitHub.

@avi-stacksavings you can keep verifying functionality for now but will need to re-test after he checks in changes. Please document any issues found though in first checking. Check overall functionality of the layout as there were a lot of changes overall.

**Comment by cyberdypro** [comment]
@stacksavings I’ve moved testimonial widget to vendor folder, it will be a common widget. Also every layout that use this widget can replace template for this widget by put a template under `themes` folder. Please check and let me know if have any wrong

**Comment by stacksavings** [comment]
@cyberdypro 

1) Check any code reading comments I made from last commit and address these

2) I don't get why the code is like this in index.php for livre-4 layout:

$layout               = LayoutEditable::getInstance('livre-lead_testimonial', null, array(

Why are you calling the sheet livre-lead_testimonial? This would break the functionality where we have pages that are passed in via query param. The base tab should always be just like "livre-lead", nothing with a "_" and text after as that is how we definite names to match a query param that is passed in.

3) I am not clear whether the testimonial has it's own CSS or it requires some CSS that is included separately in the livre-lead layout?

each widget (such as testimonial widget) must have it's own CSS and any dependencies so that front-end dev does not need to include anything else to make widget work initially. If they want to override things then they can do this (we can figure this later if needed). But, they should not have to include any CSS or any libraries (such as bootstrap).

These need to be included within the widget itself, such as in a .tpl file.

I don't think you have addressed this yet, or have you?

4) I don't understand the __construct method of the quickstart.php class.

It seems it is hard-coding about the testimonials widget. What if we have different widgets in the future? We could have like 10 widgets and layout only wants 2 of them, it has to be dynamic to handle this based on waht is called by the layout.. please keep this in mind or clarify how this working.

**Comment by avi-stacksavings** [comment]
@stacksavings  @cyberdypro 
Tested before this commit: 5a68249
Issue found:
When we keep only 2 or 1 testimonials, it makes the big white space at the bottom. Refer image below

![screenshot_316](https://cloud.githubusercontent.com/assets/20572760/25262867/e934ebfa-2678-11e7-9b72-4078911e5014.png)

Tested on: http://servicejoin.com/livre-4/index.php
Sheet Used: https://docs.google.com/spreadsheets/d/1HBZybnUJOdUokHZIU_dPeK1-2xhT3u5yAoH911cuij4/edit#gid=959060143
Tab used: livre-lead_testimonial
(try removing all testimonials and leave first 2 then white space issue appears.

**Comment by avi-stacksavings** [comment]
Tested on: http://servicejoin.com/livre-4/index.php
Sheet Used: https://docs.google.com/spreadsheets/d/1HBZybnUJOdUokHZIU_dPeK1-2xhT3u5yAoH911cuij4/edit#gid=959060143
Tab used: livre-lead_testimonial

@stacksavings  White space issue fixed
