### ISSUE TITLE
FB issue 

### ISSUE THREAD

**Issue by kuljeetbabber** [StackSavingsTeam/googlesheetslayout#5]
In C9 link -->https://bagpacks-avidayal91.c9users.io/livre-lead/unbouncepages.com/livre-lead-gen/index.php 

I tried to implement the FB code same used on Mastenia layout but following errors came:
01. FB login button not appearing but another button "connect without FB" is showing.
02. A lot of errors in console, among all some HTTPS errors are many. 
**Error in console**
01. Mixed Content: The page at 'https://bagpacks-avidayal91.c9users.io/livre-lead/unbouncepages.com/livre-lead-gen/index.php' was loaded over HTTPS, but requested an insecure script 'http://d2y5whbil7yeo8.cloudfront.net/published/jquery.ubpoverlay-1df1425.z.js'. This request has been blocked; the content must be served over HTTPS.  **So many of this type**
[console errors.txt](https://github.com/StackSavingsTeam/googlesheetslayout/files/819640/console.errors.txt)

**The text file contains all console errors**

in FTP link --> http://servicejoin.com/livre-leads-test/unbouncepages.com/livre-lead-gen/index.php
**Errors**
01. FB login button not appearing but another button "connect without FB" is showing.
02. No errors shown in console in FTP and button also not appearing 

I copied following things from Mastenia site:
01. script code
02. button code
03. js_code.js file

**Comment by stacksavings** [comment]
For this issue:

> 3) Mixed Content: The page at 'https://bagpacks-avidayal91.c9users.io/livre-lead/unbouncepages.com/livre-lead-gen/index.php' was loaded over HTTPS, but requested an insecure script 'http://d2y5whbil7yeo8.cloudfront.net/published/jquery.ubpoverlay-1df1425.z.js'. This request has been blocked; the content must be served over HTTPS. So many of this type
> console errors.txt

It is self-explanatory, there should be no confusion on this, it says what the issue is already, it is trying to use a 3rd party script from an http url. You should not be loading a 3rd party url at all, I have already said before that this needs to be copied to the project and loaded from within the project itsself.

**Comment by stacksavings** [comment]
Regarding this:

> in FTP link --> http://servicejoin.com/livre-leads-test/unbouncepages.com/livre-lead-gen/index.php
> Errors
> 
> FB login button not appearing but another button "connect without FB" is showing.
> No errors shown in console in FTP and button also not appearing

This is wrong, there are errors. You must not be understanding, when mentioned to check errors always use f12 tool and check console there. There are errors when using f12 tool and checking url from ftp. You need to address these errors. There is a 3rd party library being used, I think it is jquery, this is interfering with things as can be seen by the errors, need to figure out what is going on as this library may not be needed.

**Comment by avi-stacksavings** [comment]
Issue was body tag was not fully copied.
