### ISSUE TITLE
Testimonial widget is not working

### ISSUE THREAD

**Issue by stacksavings** [StackSavingsTeam/googlesheetslayout#56]
Check this file within the code base:

https://github.com/StackSavingsTeam/googlesheetslayout/blob/master/livre-4/index.php

Find this line in the code:

 <?php $layout->getWidget('testimonial'); ?>

This is supposed to render testimonials which are a widget but it is not working properly.

You will need to track through the code to debug why this isn't working. It was started by another developer who left he team.

**Comment by avi-stacksavings** [comment]
used widget.json to create QuickStart instance so that the widget content is initialized with the constructor.
need to debug why still the testimonials are not shown

@stacksavings 
Amit and niraj will continue in morning

**Comment by avi-stacksavings** [comment]
@stacksavings  Amit working on urgent MS task, for now Niraj is checking for render function.. as amit mentioned to check in quickstart.php

**Comment by stacksavings** [comment]
This tells me nothing and I will consider it as no progress

⁣Sent from BlueMail ​

**Comment by stacksavings** [comment]
You will need to provide a real update on this and pull in more devs

⁣Sent from BlueMail ​

**Comment by stacksavings** [comment]
Debugging an issue should not take this long to figure out where the code is failing, I need to know the exact spot it's failing, this should already have been figured out by now. The fix may take longer but figuring out where it's failing from debugging could have been done by now by any competent developer. Get me he filename and exact place in that file it's failing and any additional info.

⁣Sent from BlueMail ​

**Comment by avi-stacksavings** [comment]
Amit figured out yesterday the widget data that should be passed to the QuickStart object wasn't passed to it.. so he did that yesterday..

He had just put it in the beginning of the file..He wasnt not sure where it should be placed exactly.. you can so had niraj to figure this out.

**Comment by stacksavings** [comment]
This does not tell me anything useful. I need to know the exact current issue and what is being done to fix. You should have a Dev looking at this nonstop until it's fixed

⁣Sent from BlueMail ​

**Comment by avi-stacksavings** [comment]
dev looking into it non stop already

**Comment by stacksavings** [comment]
What is current exact status then? When debugging you can find exact point of failure,. I'm asking again what that is in code exactly. That means file and line number

⁣Sent from BlueMail ​

**Comment by FroyoAndroid** [comment]
Update 1:
 $widgetdata = file_get_contents('../vendor/widgets/testimonial/widget.json');
$layout               = Quickstart::getInstance('livre-lead_testimonial', null, $widgets);

when a widget data is send in the constructor function it hit the function > setWidgetConfig


inside that setWidgetConfig it is accpeted when the $widget data has 'widgets' key in the array


i modified the code in index.html file to something like this.
$widgetdata = file_get_contents('../vendor/widgets/testimonial/widget.json');
$widgets = array('widgets' => array($widgetdata));
$layout               = Quickstart::getInstance('livre-lead_testimonial', null, $widgets);


it now hit  if (isset($config['widgets'])) {
           foreach ($config['widgets'] as $key => $class) {

               if (in_array($key, get_object_vars($this->_widgetDefinition))) continue;
               if (!(new $class(array()) instanceof Widgets\WidgetInterface)) die("Widget \"{$class}\" definition is not valid");

               $this->_widgetDefinition->$key = (object) array(
                   'class' => $class
               );
           }
       }


But getting an error


**Fatal error: Class '{ "name": "Testimonial", "class": "TestimonialWidget", "namespace": "Widgets\\Testimonial", "assets": { "scripts": { }, "styles": [ "../vendor/stacksavings/assets/css/testimonial.css" ] } }' not found in /home/ubuntu/workspace/vendor/Quickstart.php on line 65**

**Comment by stacksavings** [comment]
Thank you for the more in depth info. 

The last dev was doing things wrong, css should go in same folder as the testimonial widget, can you modify there to add css and make it use that instead?

⁣Sent from BlueMail ​

**Comment by FroyoAndroid** [comment]
Issue fixed. **Avil to review**.

@avidayal91

**Comment by stacksavings** [comment]
Ok please go ahead and commit changes also it will be ok

⁣Sent from BlueMail ​

**Comment by stacksavings** [comment]
Please leave open, dev cannot close as I have to check...

⁣Sent from BlueMail ​

**Comment by stacksavings** [comment]
Avi has made no comment so I'm assuming he has not tested?

⁣Sent from BlueMail ​

**Comment by avi-stacksavings** [comment]
@stacksavings I tested on c9 thats why asked him to commit. Testing on FTP.

**Comment by avi-stacksavings** [comment]
@stacksavings Tested on FTP: http://servicejoin.com/livre-4/index.php
Sheet used: https://docs.google.com/spreadsheets/d/1HBZybnUJOdUokHZIU_dPeK1-2xhT3u5yAoH911cuij4/edit#gid=1090234551
tab: livre-lead_testimonial

Working fine.

**Comment by FroyoAndroid** [comment]
code commited on master

@avi-stacksavings @stacksavings

**Comment by stacksavings** [comment]
@FroyoAndroid  this seems fine for now, I don't have any additional feedback on the code. I think we can just use this way of doing it for any future widgets as it's not much extra work.
