### ISSUE TITLE
Livre-lead - Implementation

### ISSUE THREAD

**Issue by avi-stacksavings** [StackSavingsTeam/googlesheetslayout#6]
Layout folder name: livre-4

Sheet for reading data to edit the layout:
https://docs.google.com/spreadsheets/d/1HBZybnUJOdUokHZIU_dPeK1-2xhT3u5yAoH911cuij4/edit#gid=1394763281

Sheet for saving login and form submissions:
https://docs.google.com/spreadsheets/d/1E_6-X5gESKCMWK4OAJP_pr2YGwYYB5SS4XlwJlBcxS0/edit#gid=1354937986

**Comment by avi-stacksavings** [comment]
Tested and working as per this FTP URL: http://servicejoin.com/livre-4/index.php

**Comment by stacksavings** [comment]
There was an issue with the path in c9, from now on, need to test the url in c9 also and then in FTP and make sure that the path is the same (except for the http://servicejoin.com part) if it's not then something is wrong and needs to be addressed.

**Comment by avi-stacksavings** [comment]
Not marking it as complete as other 3 issues remaining.. once all issues done on this Layout. then only i will mark it complete.

**Comment by avi-stacksavings** [comment]
ready for final verification

FTP URL: http://servicejoin.com/livre-4/index.php
