### ISSUE TITLE
Livre4: google access issue

### ISSUE THREAD

**Issue by avi-stacksavings** [StackSavingsTeam/googlesheetslayout#8]
after submitting the form, its asking for google drive access first time user filling up the form.
URL tested on: http://servicejoin.com/livre-4/unbouncepages.com/livre-lead-gen/index.php

**Comment by kuljeetbabber** [comment]
The solution for the above is, we have to setup google spreadsheet.

The thing which is working behind is a script under **Tools > Script Editor**

Here, when you click on **Publish > Deploy as web app**

Following dialog box will open -
https://cloud.githubusercontent.com/assets/194400/10558251/570a5428-74c1-11e5-8ced-5dd26d3de3c4.png

**_## Now this the part to be setup carefully_**
01. Select "Execute the app" as **Me** ALWAYS
02. Select "Who has access to app" **Anyone, even anonymous** ALWAYS

You can also refer to https://cloud.githubusercontent.com/assets/194400/10558251/570a5428-74c1-11e5-8ced-5dd26d3de3c4.png

**Comment by avi-stacksavings** [comment]
Google access issue resolved.

Tested on: http://servicejoin.com/livre-4/index.php
