### ISSUE TITLE
Libre: folder structure

### ISSUE THREAD

**Issue by avi-stacksavings** [StackSavingsTeam/googlesheetslayout#9]
Need to move index.php in the root folder

**Comment by avi-stacksavings** [comment]
Folder structure changed.

http://servicejoin.com/livre-4/index.php

**Comment by stacksavings** [comment]
this was not fixed properly.

**Comment by stacksavings** [comment]
When I go into the project in my c9 workspace and run the project, then access this url:

https://google-sheets-stacksavingsdev.c9users.io/livre-lead/index.php

I get:

a redirect to this url:

https://google-sheets-stacksavingsdev.c9users.io/livre-lead/unbouncepages.com/livre-lead-gen/index.html

and then a message:

Not Found

The requested URL /livre-lead/unbouncepages.com/livre-lead-gen/index.html was not found on this server.

Apache/2.4.7 (Ubuntu) Server at google-sheets-stacksavingsdev.c9users.io Port 443

**Comment by stacksavings** [comment]
See above, something is not right, try this for yourself also in c9.. the path seems ok in the FTP servicejoin url but it needs to be right in the repo also, something weird is going on..

**Comment by avi-stacksavings** [comment]
no, you need to open livre-4 folder in c9 too.

**Comment by avi-stacksavings** [comment]
deleted the old layout.. please pull in and test with "livre-4" layout
